[package]
name = "test_anndata"
version = "0.1.0"
edition = "2021"

[dependencies]
anndata = "0.6.1"
anndata-hdf5 = "0.5.0"
anyhow = "1.0.95"
libsw = "3.4.0"
nalgebra = { version = "0.33.2", features = ["io", "sparse"] }
nalgebra-sparse = { version = "0.10.0", features = ["io"] }
sprs = "0.11.2"
